index-prefix: ${searchsystem:openeuler_test}

elasticsearch:
  host: ${eshost}
  username: ${esusername}
  password: ${espassword}
  port: ${esport}

#网站埋点数据库

tracker-index: ${trackerindex:openeuler_tracker}
tracker:
  host: ${teshost}
  username: ${tesusername}
  password: ${tespassword}
  port: ${tesport}

server:
  port: 8080